### PR TITLE
Update peerDependencies to support Grunt 1.0

### PR DESCRIPTION
**Pull request by grunt-updater2**
Update peerDependencies to support Grunt 1.0

Hello,

This is an automated issue request to update the `peerDependencies` for your Grunt plugin.
We ask you to merge this and **publish a new release on npm** to get your plugin working in Grunt 1.0!

Read more here: http://gruntjs.com/blog/2016-02-11-grunt-1.0.0-rc1-released#peer-dependencies
Also on Twitter: https://twitter.com/gruntjs/status/700819604155707392

If you have any questions or you no longer have time to maintain this plugin, then please let us know in this thread.

Thanks for creating and working on this plugin!

(P.S. Close this PR if it is a mistake, sorry)

### CODE REVIEW

**Comment by sdebionne** [comment]
@automatonic Hi, the current package configuration prevent to use this plugin with grunt 1.0x with `npm` 2.0:

```
npm ERR! peerinvalid The package grunt@1.0.1 does not satisfy its siblings' peer
Dependencies requirements!
npm ERR! peerinvalid Peer grunt-hogan@0.3.0 wants grunt@~0.4.5
```
Could you please merge this  pull request, and bump the version to 3.1?
Thanks!

**Comment by automatonic** [comment]
I will try and get this published tonight if i can.

**Comment by sdebionne** [comment]
Awesome thanks!

**Comment by automatonic** [comment]
@sdebionne 0.3.1 is published to NPM. Let me know if you hit any issues.

**Pull request merged**
